image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t phildue/vslam:dev --target developer .
    - docker build -t phildue/vslam:builder --target builder .
    - docker build -t phildue/vslam:runtime --target runtime .
test:
  stage: test
  script:
    - docker run phildue/vslam:builder /bin/bash -c "colcon test --event-handler console_direct+ ; colcon test-result"

evaluate:
  stage: test
  script: 
    - docker run -v/home/phil/dataset:/mnt/dataset phildue/vslam:runtime python3 script/evaluate.py --experiment_name ci_$CI_COMMIT_REF_NAME --sequence_id rgbd_dataset_freiburg2_desk --workspace_dir /app/vslam/ --commit_hash $CI_COMMIT_SHA

#lint:
#  stage: test
#  only: [master,development]
#  script:
#    - mkdir lint_results
#    - docker run -v $(pwd)/lint_results:/results/ phildue/vslam:builder ament_clang_format --xunit-file /results/clang_format.xunit.xml"
#    - docker run -v $(pwd)/lint_results:/results/ phildue/vslam:builder ament_clang_tidy --xunit-file /results/clang_tidy.xunit.xml"
#    - docker run -v $(pwd)/lint_results:/results/ phildue/vslam:builder ament_flake8 --linelength 200 --xunit-file /results/flake8.xunit.xml"

#deploy-container:
#  stage: deploy
#  only: [master]
#  script:
#    - docker push phildue/vslam:dev
#    - docker push phildue/vslam:runtime
