
/NodeRgbdAlignment:
  ros__parameters:
    direct_icp:
      minGradientIntensity: 5.0
      minGradientDepth: 0.01
      maxGradientDepth: 0.3
      maxDepth: 5.0
      nLevels: 4.0
      maxIterations: 100.0
      minParameterUpdate: 0.0001
      maxErrorIncrease: 10.5
      maxPoints: 307200.0
    motion_model:
      variance: 0.03
      maxTranslationalVelocity: 1000.0
      maxAngularVelocity: 1000.0
    sync:
      queue_size_max: 50
      queue_size_min: 10
      max_interval: 0.02
    tf:
      base_link_id: world
      frame_id: odom
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
/NodeReplayer:
  ros__parameters:
    delay: 0.0
    duration: -15.0
    timeout: 0.1


