
/NodeRgbdAlignment:
  ros__parameters:
    direct_icp:
      nLevels: 4.0
      maxIterations: 100.0
      minParameterUpdate: 0.0001
      maxPoints: 307200.0
    sync:
      queue_size: 20
      max_interval: 0.20
    tf:
      base_link_id: world
      frame_id: odom
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
/NodeReplayer:
  ros__parameters:
    delay: 0.0
    duration: -10.0
    timeout: 0.1


