
/NodeOdometry:
  ros__parameters:
    features:
      intensity_gradient_min: 5.0
      depth_gradient_min: 0.01
      depth_gradient_max: 0.3
      depth_min: 0.0
      depth_max: 8.0
      grid_size: 10.0
      n_levels: 4
    odometry:
      n_levels: 4
      max_iterations: 40
      min_parameter_update: 0.0001
      max_error_increase: 10.0
    predictor:
      information: 10.0
    keyframe_selection:
      max_entropy_reduction: 0.1
    sync:
      queue_size_max: 50
      queue_size_min: 10
      max_interval: 0.02
    tf:
      base_link_id: world
      frame_id: odom
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
/NodeLoopClosures:
  ros__parameters:
    min_entropy_ratio: 0.9
    candidate_selection:
      max_translation: 0.5
      min_features: 500
    features:
        intensity_gradient_min: 5.0
        depth_gradient_min: 0.01
        depth_gradient_max: 0.3
        depth_min: 0.0
        depth_max: 8.0
        grid_size: 10.0
        n_levels: 4
    aligner:
      coarse:
        max_iterations: 30
        min_parameter_update: 0.0001
        max_error_increase: 10
      fine:
        n_levels: 4
        max_iterations: 40
        min_parameter_update: 0.0001
        max_error_increase: 10
    logimg:
      LoopClosures:
        show: 1
      LoopClosuresRatioTest:
        show: -1
/NodePoseGraph:
  ros__parameters:
    optimizer:
      loss_threshold: 0.5
/NodeReplayer:
  ros__parameters:
    delay: 0.0
    duration: -15.0
    timeout: 0.1


